### ISSUE TITLE
auth0 account creation

### ISSUE THREAD

**Issue by SteveC** [auth0/wp-auth0#192]
On the plugin activation screens you can

* click to sign up for free - goes to auth0.com
* click to social - sends you to auth0 sign in page
* click to enterprise - sends you to auth0 sign in page

Can these instead go to an account signup workflow? Do we have one available?

If not - can it highlight the sign up tab rather than login?

Maybe the workflow could be "do you have an auth0 account?" yes/no then something that warns that you have to create an account?

Or maybe you thought of all of this already?

**Comment by glena** [comment]
So we will see how it works creating an internal page in the plugin to embed the Lock widget in signup mode. It will redirect to the auth0 callback where the user will continue with the tenant creation (instead of sending them to auth0.com).

Also, I will file an issue to see if we can disable the signup option in the consent login page.

**Comment by glena** [comment]
@SteveC can you help with the copy for the title and the paragraph? 

IMO, it should be clear that the user is signing up to an external service that will be used by the plugin, what do you think?

![image](https://cloud.githubusercontent.com/assets/5647310/14683546/aa1726c8-0701-11e6-9312-7655b72cec89.png)

**Comment by SteveC** [comment]
title: Sign Up with Auth0

text: To get started with the plugin we need you to sign up with Auth0 below. It should only take a second:

**Comment by glena** [comment]
done
