### ISSUE TITLE
Broken (or confusing?) flow in creating passwordless auth

### ISSUE THREAD

**Issue by jgelsey** [auth0/wp-auth0#194]
Reproduction steps:
-new WP site
-new Auth0 account
-go to plugin settings->advanced and turn on `use passwordless login`
When passwordless via magic link, no email seems to work:
![image](https://cloud.githubusercontent.com/assets/548826/14447193/11821292-0012-11e6-9e35-5957e3668836.png)

When passwordless via SMS or Social, get a blank Lock:

![image](https://cloud.githubusercontent.com/assets/548826/14447203/2a60dfa0-0012-11e6-9f88-876d61a5eaff.png)

Likely can be fixed with enhanced guidance of how to configure correctly in the Auth0 dashboard? But not clear to the casual observer.

**Comment by glena** [comment]
We are going to check if the selected connection is enabled and if not, it will show an alert explaining that this should be configured in manage.auth0.com too

**Comment by SteveC** [comment]
"Please make sure to turn on passwordless authentication on your [Auth0 dashboard][link]"

?

**Comment by SteveC** [comment]
Can we do away with the setting entirely and just use it if the dashboard has it turned on? So automatically inherit the setting from the dashboard?

**Comment by glena** [comment]
I wouldnt do that automatically, but it is not a bad idea to check this and ask the user if he want to enable passwordless

**Comment by SteveC** [comment]
Why would automatic be a bad idea? I'm just curious...

**Comment by glena** [comment]
Summing up, we are going to do 2 things:

- each time the user changes something in the plugin related to passwordless, we are going to check if it is configured in their account

- when we provision the user, we will check if there is any passwordless connection enabled in their account, and ask the user if they want to enable passwordless in their site

This is because is better to avoid:

- duplicate the UI to set up the social connections (it does a lot of stuff)
- having out of date settings in the plugin (if we change, add or remove connections in the dashboard)
- having sync issues between different wordpress sites and the dashboard when things are changed in different places.
