### ISSUE TITLE
Can not login user after being added in both WP and Auth0

### ISSUE THREAD

**Issue by delmicio** [auth0/wp-auth0#340]
I'm provisioning every new user added through the wordpress admin panel to Auth0 using the [create user endpoint](https://auth0.com/docs/api/management/v2#!/Users/post_users)

1. On `user_register` action create the user on Auth0 with the same email and password. DONE
2. Login in wordpress using Auth0 plugin. FAIL

`http://localhost/index.php?auth0=1&code=mdivTbhcIXjfNn0w&state=eyJpbnRlcmltIjpmYWxzZSwidXVpZCI6IjU5OWJhYzU1OTIxNDAiLCJzdGF0ZSI6Im5vbmNlIn0%3D`
![image](https://user-images.githubusercontent.com/2908209/29548501-c186316c-86d7-11e7-8bba-787d0554c44b.png)

https://github.com/auth0/wp-auth0/blob/51aaaecaff9b178ac523f284b98c231a0ee7f748/lib/WP_Auth0_LoginManager.php#L163

Auto provisioning option is ON.
Link users with same email is OFF and have tried with ON as well.

What's the problem with my procedure?

**Comment by coperator** [comment]
Although your question is from some time ago, I want to provide an answer.
I guess, the problem is, that you need to also set the auth0 user's mail address to verified, so that the wp_auth plugin joins the auth0 user with the wordpress user. A verified mail address is necessary to avoid hijacking existing wordpress users with a new registered auth0 user.

**Comment by joshcanhelp** [comment]
@delmicio - Apologies for the very delayed response. 

I'm a little confused here. You wrote custom code to create a user in Auth0 when they register on your WordPress site? If you're using the WordPress plugin then your standard wp-login.php form is replaced with an Auth0 form so registration happens the other way around, in Auth0 and sent back to WordPress. 

Your error message is telling me that you're trying to register someone that already exists in the database. So I'm guessing that you're creating the user in WordPress and when the login comes back, it looks for the Auth0 data (`usermeta` fields), doesn't find anyone with that, but then can't create a new user because that email is taken. If you do need to create the user via the management API rather than the sign-up form, look at the `WP_Auth0_UsersRepo::find_auth0_user()` and `WP_Auth0_UsersRepo::update_auth0_object()` methods to see what needs to be saved on a new user in WP. 

@coperator - Thanks for attempting to help! The verified email error is pretty explicit about what it asks for an includes a link to re-send the email.

**Comment by delmicio** [comment]
I'm not longer interested on solving this, project was dissolved.
