### ISSUE TITLE
Optionally load client ID, secret and domain from environment

### ISSUE THREAD

**Issue by Floppy** [auth0/wp-auth0#480]
We have multiple environments that we keep in sync with database backups cloned between them. Obviously this confused the Auth0 plugin as it doesn't have the right credentials any more. 

Loading the credentials from the environment in a 12-factor app style would make this a lot easier. Perhaps if the values are blank in the database they could be loaded from the env? Another issue here is the user migration token, which could perhaps be generated in a more stable fashion so it doesn't need to be stored in the database?

**Comment by joshcanhelp** [comment]
@Floppy - Thank you for the suggestion on this. We were considering something like this for sensitive data storage like the ones you mentioned. WordPress convention is to define a constant in wp-config.php, rather than a .env file. Would that work for your purposes? Then we don't have to load a separate env-parsing library.

**Comment by joshcanhelp** [comment]
Tracking progress in the [`add-env-settings-support`](https://github.com/auth0/wp-auth0/compare/dev...add-env-settings-support)

**Comment by Floppy** [comment]
Yeah, it's probably best to stick to the wordpress standard. We can always use an env loader inside our `wp-config.php` to do the next step.

**Comment by joshcanhelp** [comment]
Fixed in #509, merged into `dev`. Release coming soon!
