### ISSUE TITLE
Auth0 users with different accounts but same username will not be able to log into the site

### ISSUE THREAD

**Issue by RedEdgeKatelyn** [auth0/wp-auth0#52]
With the [recent commit] (https://github.com/auth0/wp-auth0/commit/40377d7a14417d3ceea450bc5822007bdee3f9d5), the error triggered by username collisions is no longer suppressed, but this means that users different accounts with the same username will receive an error message telling them that their username already exists. 

The issue arises because Auth0 usernames are simply the first part of the email address, up to the @ symbol. But, several users can have the same username, since Auth0 only requires the full email to be unique.

Would it be possible to switch from using Auth0 usernames (which are not unique) to Auth0 email addresses (which are) for the WP username?

**Comment by glena** [comment]
It is not as easy as change from username to email. The problem is that in cases where the connection (ie twitter or instagram) doesn't provide an email and only the username. As soon we figure out the best way to handle it we will release a new version.

The idea of the last update is to prevent the security issue that you notify us.

Thank you very much for you collaborations.

**Comment by glena** [comment]
Done => https://github.com/auth0/wp-auth0/pull/55/files#diff-6e06369d1eb2c0b065f6192a23eed41cR39
