### ISSUE TITLE
Automatically create user in Wordpress through Post-User Registration Hook

### ISSUE THREAD

**Issue by nmoinvaz** [auth0/wp-auth0#527]
Some of our Auth0 users are created via the Auth0 API, it would be great if there was a way or an example of creating a Wordpress user through the Auth0 post-user registration hook. So that when a user was added in Auth0 an associated user would be created in Wordpress with the wp-auth0 plugin. Thanks.

**Comment by joshcanhelp** [comment]
Hi @nmoinvaz,

> Some of our Auth0 users are created via the Auth0 API

The Management API? In another app?

> it would be great if there was a way or an example of creating a Wordpress user through the Auth0 post-user registration hook

The post-registration hook happens *after* registration so that wouldn't really work. 

> So that when a user was added in Auth0 an associated user would be created in Wordpress with the wp-auth0 plugin. 

That happens automatically when a user logs in. If you create the Auth0 user, then just login with those credentials and the WP one is created automatically. 

Let me know if I'm not understanding your suggestion here.

**Comment by nmoinvaz** [comment]
I see. Thanks.
