### ISSUE TITLE
1Password Compatibility

### ISSUE THREAD

**Issue by oloflarsson** [auth0/wp-auth0#627]
### Description
The Auth0 setup wizard on the settings page within Wordpress triggers the 1Password browser plugin. First of all it pops up and seems to believe it should fill out some hidden field. Secondly it inputs credentials into the domain and key form.

<img width="2048" alt="one" src="https://user-images.githubusercontent.com/421009/53554481-25d25d80-3b40-11e9-9230-4dba900f7b9b.png">
This popup appears and can simply be clicked away. It's just a little annoying. Does it react to some hidden form in the dialog behind?

<img width="2048" alt="two" src="https://user-images.githubusercontent.com/421009/53554506-3256b600-3b40-11e9-8234-5d5dbb9631b2.png">
The "Enter your tenant Domain:" input field is prefilled with something irrelevant. That way the user does not get to see "youraccount.auth0.com", because of that I ended up writing just the "youraccount" part and it took me some time to figure out what's wrong.

### Environment
* WP-Auth0 version: 3.9.0
* WordPress version: 5.1
* PHP version: 7.0.33-0ubuntu0.16.04.1
* Browser version: Google Chrome 72.0.3626.119 (Official Build) (64-bit)
* 1Password Version: 7.2.4 (70204000) AgileBits Store

**Comment by joshcanhelp** [comment]
@oloflarsson - I've seen that on my end as well. 1Password is seeing the `password` field in that modal and triggering your extension. I looked through the 1Password forum and see a few posts on that saying it's not possible:

https://discussions.agilebits.com/discussion/12412/how-to-tell-extensions-to-ignore-a-form-field

https://discussions.agilebits.com/discussion/96661/disabling-1password-x-for-specific-fields-forms-web-developer-question

https://discussions.agilebits.com/discussion/54532/disable-password-prompt-for-form

When it was a `text` input type that popup did not show but then the token appeared, which is not what we want. One option would be to use the Universal Login page (which is recommended anyways) and turn off the prompt for the WordPress site (since the password will be on a different domain).
