### ISSUE TITLE
WP_Auth0_Routes::migration_ws_login, 401	Invalid Credentials

### ISSUE THREAD

**Issue by saucompeng** [auth0/wp-auth0#633]
I add Login by auth0 plugin to my wordpress, I have an error like **WP_Auth0_Routes::migration_ws_login, 401	Invalid Credentials** when I try Login script at custom database.

Then I install a new wordpress for test to new droplet, I installed plugin successfully. What is the problem at my main wordpress?

**Comment by joshcanhelp** [comment]
@saucompeng - Thank you for the report here!

A 401 from that endpoint means that the request is not allowed. Do you have **Auth0 > Settings > Advanced > "Migration IPs Whitelist"** in the plugin turned on? That will restrict by IP address, though the default incoming Auth0 IPs should be whitelisted automatically. Also, check to make sure the Migration Token on the same settings tab matches what it in Auth0 > **Connections > Databases > DB connection used > Custom Database tab** (both scripts).

**Comment by saucompeng** [comment]
Thank you for your response.

I checked what you said. Migration IPs white list comes automaticliy when I use user migration wizard. It's ok. And I checked token which is same both of pages.

When I try "Get User" script, it gets my account information successfully. But Login script says, "Wrong email or password."

**Comment by joshcanhelp** [comment]
That sounds like you might be using the wrong password, then. The main difference between those 2 scripts is that Get User looks for the existence of a user while Login checks your password. Keep in mind that once the user has been migrated to Auth0 (logged in once with the Auth0 login form, you should see a **Delete User Data** button on their WordPress profile edit page), the password that's used is in Auth0, not WordPress. Is the password was changed only in Auth0 then it will not be the same as WordPress (which is fine because the Auth0 password is always used).

**Comment by saucompeng** [comment]
The password is true. Same time, my colleague tries with his account, the problem is the same and continues :/

**Comment by joshcanhelp** [comment]
Looks like you deleted out the issue template we've got set for this repo so can you tell me what version of the plugin, WordPress, and PHP you're using? 

This sounds like an issue with the API token saved but that should only happen when the plugin is updating (judging from the mention of `WP_Auth0_DBManager::install_db`). Does that error show up in the plugin error log on each attempt at logging in? Can you try deactivating the plugin then reactivating and see if that helps? Also, try [generating](https://auth0.com/docs/api/management/v2/get-access-tokens-for-test) and saving a new Management API Token in the "API Token" field under the **Basic** tab in the plugin settings?

**Comment by saucompeng** [comment]
Sorry about deleting.

My wordpress version is 5.0.3, Php version: 7.0.32, Woocommerce version: 3.5.4

**Does that error show up in the plugin error log on each attempt at logging in?**
Only show when I use "User Migration Setup", other login attempts, it gives an error like: "invalid credential"

**Can you try deactivating the plugin then reactivating and see if that helps? **
I've erased and reinstalled the Plugin. Nothing changed.

**Also, try generating and saving a new Management API Token in the "API Token" field under the Basic tab in the plugin settings?**
I tried it nothing changed, also when reinstalling the plugin, token changing automatically.

**Comment by joshcanhelp** [comment]
Thanks for that! How about WP-Auth0, is that on the latest?

**Comment by saucompeng** [comment]
> Thanks for that! How about WP-Auth0, is that on the latest?

Version 3.9.0

**Comment by joshcanhelp** [comment]
Alright, that's the latest. 

We are just finishing up a troubleshooting guide for user migrations if you want to take a look. Not officially reviewed or published but might help you figure out the root cause:

https://github.com/auth0/docs/blob/b12cad7d940d6a19dd1fb4786ec17750191aea46/articles/cms/wordpress/user-migration.md#troubleshooting

You might try running through the manual setup steps as well in case that catches something. Let me know if you get stuck or if one of the steps helps you figure out the issue.

**Comment by joshcanhelp** [comment]
@saucompeng - Were you able to solve your issue here? We're gearing up for a release soon and want to make sure I include any fixes, if needed. 

Thanks!

**Comment by saucompeng** [comment]
@joshcanhelp I couldn't fix the problem yet. Please help me

**Comment by joshcanhelp** [comment]
Did you walk through the troubleshooting guide above? What is the error you're seeing when you follow those steps? Did you get stuck anywhere during the steps.

**Comment by saucompeng** [comment]
I changed script Line 30 to callback(wpUser.error); it gives an error like "invalid credentials", And I changed my password again, it gives same error also.

**Comment by saucompeng** [comment]
Finally, I found the problem. reCaptcha plugin blocks login :( I disabled it and login succesfully.

**Comment by joshcanhelp** [comment]
Thanks for the update @saucompeng! If you can post a link to the plugin you're using, I'll take a look and see if there's something we can do differently on our end to be more compatible.
