### ISSUE TITLE
Allow loading / saving Shipping Addresses used by WooCommerce in Auth0 Profile

### ISSUE THREAD

**Issue by cancan101** [auth0/wp-auth0#76]
It would be great if Auth0 could be used to load / store the information needed by the user when checking out in WooCommerce.

This should exclude payment information (CC#s) since that should be stored by the payment gateway.

**Comment by glena** [comment]
Hi @cancan101 this feature you are asking are out of the scope of this plugins. It is a very specific feature that must support a lot of different plugins. For this reason, it is not in our backlog.

Anyway, we can give you some guidance. In fact, It shouldn't harder than add an API call to https://auth0.com/docs/api/v2#!/Users/patch_users_by_id to set the user/app metadata.

Also, we can add an action on the user creation in the Auth0 plugin in order to make it easy to get the info from the auth0 profile and populate your database.

The same happens with issue #77.

**Comment by cancan101** [comment]
>we can add an action on the user creation in the Auth0 plugin in order to make it easy to get the info from the auth0 profile and populate your database.
This sounds good, but what to do about pulling in the newest changes from Auth0 profile each time the user logs in to WP?

**Comment by glena** [comment]
The plugin always get the user profile in order to find the WP user to login, so this action could be fired on each login with this data. I am thinking in something like
```
function Auth0UserLogin((int)$user_id,(stdClass) $profile, (book) $new_user)
```

**Comment by cancan101** [comment]
Okay, so you are saying some hook in WP that will get called when an Auth0 user logs in that gets passed the user's auth0 profile contents?

**Comment by glena** [comment]
exactly

**Comment by glena** [comment]
Hey @cancan101 I've released a new version with the action we talked. I updated the readme  (https://github.com/auth0/wp-auth0#interating-with-the-plugin) with info about it.
