### ISSUE TITLE
Support Storing Stripe id in Auth0

### ISSUE THREAD

**Issue by cancan101** [auth0/wp-auth0#77]
Ideally the stripe id for the customer would be storable / loadable by Auth0 plugin such that WooCommerce + one of the Stripe plugins could use the token for loading saved payment information. 

Per the Stripe docs:
>Once you've created a customer, you should store its id in your own database so you can refer to it later when communicating with stripe. 

and [more here](https://stripe.com/docs/api#retrieve_customer)

Stripe plugins for WooCommerce:
* https://wordpress.org/plugins/stripe-for-woocommerce/
* http://www.sellxed.com/shop/en/wordpress-woocommerce-stripe-zahlungs-plugin.html
* http://www.woothemes.com/products/stripe/
* https://wordpress.org/plugins/striper/

There are [even more for WordPress in general](https://stripe.com/docs/libraries).

**Comment by glena** [comment]
Hi @cancan101 this feature you are asking are out of the scope of this plugins. It is a very specific feature that must support a lot of different plugins. For this reason, it is not in our backlog.

Anyway, we can give you some guidance. In fact, It shouldn't harder than add an API call to https://auth0.com/docs/api/v2#!/Users/patch_users_by_id to set the user/app metadata.

Also, we can add an action on the user creation in the Auth0 plugin in order to make it easy to get the info from the auth0 profile and populate your database.

The same happens with issue #76.
