### ISSUE TITLE
The new version of this plugin, 5.0.0, cannot be found on wordpress plugin repository.

### ISSUE THREAD

**Issue by mnbro** [auth0/wp-auth0#855]
### Reproduction

- Step 1..
- Step 2..
- ...

### Environment

- **Version of this library used:**
- **Which framework are you using, if applicable:**
- **Other modules/plugins/libraries that might be involved:**
- **Any other relevant information you think would be useful:**

**Comment by mnbro** [comment]
The new version of this plugin, 5.0.0, cannot be found on wordpress plugin repository.

**Comment by evansims** [comment]
Hi @mnbro 👋 Thanks for your question! This is intentional and part of a progressive rollout schedule.

We're releasing the plug-in to users with Composer-based installs first, and will be progressively rolling it out to everyone through WordPress.org in the coming weeks.

Since v5 is a complete rewrite of the plug-in and represents a significant amount of changes, we feel a slow roll out makes sense. Anyone can opt in to install it immediately with Composer in the meantime.

Thanks again for your question

**Comment by mnbro** [comment]
Thank you for clarifying it!
