### ISSUE TITLE
Auth0 PHP 8 support?

### ISSUE THREAD

**Issue by neidenmark** [auth0/wp-auth0#859]
Im using Auth0 as a IDP for my Wordpress site. 
Now the hosting provider has removed support for PHP 7.4 and forced upgrade to PHP 8.

When logging in the Auth0 plugin yields the following error:
Warning: Undefined array key "scope" in /customers/a/9/0/wss.se/httpd.www/wp/wp-content/plugins/auth0/lib/api/WP_Auth0_Api_Client_Credentials.php on line 84 Warning: Cannot modify header information - headers already sent by (output started at /customers/a/9/0/wss.se/httpd.www/wp/wp-content/plugins/auth0/lib/api/WP_Auth0_Api_Client_Credentials.php:84) in /customers/a/9/0/wss.se/httpd.www/wp/wp-includes/pluggable.php on line 1078 Warning: Cannot modify header information - headers already sent by (output started at /customers/a/9/0/wss.se/httpd.www/wp/wp-content/plugins/auth0/lib/api/WP_Auth0_Api_Client_Credentials.php:84) in /customers/a/9/0/wss.se/httpd.www/wp/wp-includes/pluggable.php on line 1079 Warning: Cannot modify header information - headers already sent by (output started at /customers/a/9/0/wss.se/httpd.www/wp/wp-content/plugins/auth0/lib/api/WP_Auth0_Api_Client_Credentials.php:84) in /customers/a/9/0/wss.se/httpd.www/wp/wp-includes/pluggable.php on line 1080 Warning: Cannot modify header information - headers already sent by (output started at /customers/a/9/0/wss.se/httpd.www/wp/wp-content/plugins/auth0/lib/api/WP_Auth0_Api_Client_Credentials.php:84) in /customers/a/9/0/wss.se/httpd.www/wp/wp-includes/pluggable.php on line 1082 Warning: Cannot modify header information - headers already sent by (output started at /customers/a/9/0/wss.se/httpd.www/wp/wp-content/plugins/auth0/lib/api/WP_Auth0_Api_Client_Credentials.php:84) in /customers/a/9/0/wss.se/httpd.www/wp/wp-includes/pluggable.php on line 1416 Warning: Cannot modify header information - headers already sent by (output started at /customers/a/9/0/wss.se/httpd.www/wp/wp-content/plugins/auth0/lib/api/WP_Auth0_Api_Client_Credentials.php:84) in /customers/a/9/0/wss.se/httpd.www/wp/wp-includes/pluggable.php on line 1419

**Comment by evansims** [comment]
Hi @neidenmark 👋 Due to technical reasons, PHP 8.0+ is unsupported in V4 of our WordPress plugin, and mileage may vary as far as experience. https://github.com/auth0/wp-auth0/issues/842

We are rolling out a new major of our WordPress plugin, V5, which includes PHP 8.0+ support, and support for WordPress 6.0+. It is not live on WordPress.org's plugin marketplace quite yet, but will be in the upcoming weeks. Meanwhile, it can be installed manually by downloading the ZIP of a release, such as https://github.com/auth0/wp-auth0/releases/tag/5.0.0, and extracted to your plugins directory.

Note that we have identified a bug with activating the plugin in some configurations, which we are preparing a 5.0.1 bugfix release for yet this week.
