### ISSUE TITLE
simple plugin for WordPress

### ISSUE THREAD

**Issue by aiiddqd** [auth0/wp-auth0#868]
Why are you making difficult decisions?

How about making a simple WP plugin that just works?

i tried different approaches:
- install via wp org - not working
- install via composer - not working

all solutions - not working.

what's stopping you from making a simple plugin to make it work?

do you have anything that works?

P.S. I can help make a working solution, but I need to understand why you complicate things so much

**Comment by evansims** [comment]
Hi @uptimizt 👋 Sorry to hear you're having issues, but your message doesn't provide any details to help you in troubleshooting. What does “not working” mean here, and which version of the plugin are you trying to install?

**Comment by aiiddqd** [comment]
for example,

I need simple page for login

like this https://dev.to/enter

but:
- I install plugin https://wordpress.org/plugins/auth0/
- I added apps to Auth0 dashboard
- set all keys and secrets

And nothing.

I don't understand how to make this work.

**Comment by aiiddqd** [comment]
how i see it:
- simple base steps after install plugin
- set id, keys and secrets
- step by step instructions in plugin
- add shortcode for make simple single page for auth
- add checkbox for auto integrate form to base login forms WP

if it's ok, i'm ready to help make it

**Comment by evansims** [comment]
Hi @uptimizt 👋 The README provides complete instructions for installing and configuring the plugin — there isn't anything more to it than what is covered there.

Do you see the plugin in your admin sidebar? Have you tried opening an incongito browser and logging in after enabling it? You should see the Universal Login instead of the standard WordPress login form after enabling.

> And nothing.

Did you enable the plugin to take over authentication, under Options?

<img width="560" alt="CleanShot 2023-02-05 at 20 18 39@2x" src="https://user-images.githubusercontent.com/3093/216868126-7903cbe1-58a7-4593-b6d8-36b6e2d53cf2.png">
