### ISSUE TITLE
5.2 configuration help - new registration: WP usersnames set to auth0 id rather than auth0 "username" 

### ISSUE THREAD

**Issue by blakmarkit** [auth0/wp-auth0#894]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/wordpress#readme) and the [documentation](https://auth0.com/docs/customize/integrations/cms/wordpress-plugin), and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/wordpress/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Was previously using v4 of the auth0 plugin. Testing migration to v5. I have a few different quirks that I'm trying to understand about how the plugin is/should be configured. The documentation here and on the auth0 site do not appear to be clear and/or relevant (still v4). 

First, when I register a new account (Universal Login Classic), the WP username is being set to the auth0 ID string, and not the auth0 username (set in the Universal Login register field). Is there a plugin preference that would correct this? 

Second, v4 would send the user to a `wp_die` page that prompts the user to to verify their email before signing in—v5 appears to redirect them to the site, logged in, without verifying, but their email address doesn't appear in the user data until they verify (via the verification email) and sign in again. Is this expected behavior or a configuration issue? 

Third, is there a way to set/map the Name (Nickname) in WP? Also the WP First and Last Name fields? 

### Reproduction

Options:
- Enable Authentication: Enabled
- Connection Matching: Flexible
- Missing Users: Create account

Sync:
- Sync Frequency: 15 minutes
- On-Demand Changes: Disabled
- User Creation: Enabled
- User Deletion: Enabled
- User Updates: Enabled

### wp-auth0 version

5.2

### WordPress version

6.52

### PHP version

8.2.14

**Comment by evansims** [comment]
Hi @blakmarkit 👋

> First, when I register a new account (Universal Login Classic), the WP username is being set to the auth0 ID string, and not the auth0 username (set in the Universal Login register field). Is there a plugin preference that would correct this?

I'm afraid this isn't an option; doing so introduces conflicts in Auth0 configurations where multiple Connections might be used or when a user has multiple social accounts associated with one identity. Usernames can potentially be reused in those scenarios. This turned out to be a very common point of confusion for v4 users, so it was removed with the latest release.

> Second, v4 would send the user to a wp_die page that prompts the user to to verify their email before signing in—v5 appears to redirect them to the site, logged in, without verifying, but their email address doesn't appear in the user data until they verify (via the verification email) and sign in again. Is this expected behavior or a configuration issue?

This is intentional; the plugin doesn't allow unverified emails to be tied to the WP account as a security measure.

If you need to, you could fully override and control this behavior using Actions. There are lots of templates in there for these sorts of things. I see one that blocks user logins until their email is verified, for example.

Using the Passwordless (email) connection type is also a great option, as it requires a verified email by necessity.

> Third, is there a way to set/map the Name (Nickname) in WP? Also the WP First and Last Name fields?

Nothing is built in to support this presently, but this could be achieved with a custom code/plugin of your own — just tie into the standard `edit_user_created_user` (user created), `profile_update`, and `deleted_user` WordPress hooks.

Any changes made to the WordPress user will get sync'd back to Auth0's user management in the next plugin background sync.

**Comment by blakmarkit** [comment]
Hi @evansims thanks for the explanations! 

> Usernames can potentially be reused in those scenarios. This turned out to be a very common point of confusion for v4 users, so it was removed with the latest release.

Good to know. I wasn't sure if I was misconfiguring something, between the WP account creation settings and the Auth0 plugin's account creation settings. 

> If you need to, you could fully override and control this behavior using Actions. There are lots of templates in there for these sorts of things. I see one that blocks user logins until their email is verified, for example.

Thanks for that pointer. I've set up that first action. Would it also be in Actions to redirect a user to a "please verify your email" page after registration? 

Is there documentation anywhere about what each of the plugin's new settings does, especially the options in the `Advanced` section? I'm having cookie/session issues where I keep getting logged out what seems like every few minutes (or even seconds).
