### ISSUE TITLE
User completes ULP, but not logged in to Wordpress

### ISSUE THREAD

**Issue by tlNightfoxAudio** [auth0/wp-auth0#908]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/wordpress#readme) and the [documentation](https://auth0.com/docs/customize/integrations/cms/wordpress-plugin), and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/wordpress/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [x] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

We are hoping to switch to a new Wordpress host to gain some page speed. We spun up a server with [Rocket.net](https://rocket.net/). They use Cloudflare and the Enterprise CDN. I had a copy of the current live site made and migrated to the new server.

When you attempt to login, it goes through the full Auth0 ULP process fine, but when it sends the user back to the website, it is still asking the user to login. There are no errors in Auth0 or the Auth0 Wordpress plugin. There is a console error that says " Auth0 cannot find node with id ‘auth0-login-form’”.

The only difference between the two environments is the host. Is there a URL or cookie [Rocket.net](https://rocket.net/) or Cloudflare could be blocking?

### Reproduction

1. Click "login" on website
2. Complete Auth0 ULP process
3. User returned to correct Redirect URL, but is not logged in to an account

### wp-auth0 version

4.6.0

### WordPress version

6.5.5

### PHP version

8.1

**Comment by evansims** [comment]
Hi @tlNightfoxAudio 👋 I'm afraid support for v4 of the WordPress plugin has been deprecated. Please upgrade to v5 so we can continue providing assistance.

To your specific situation, though, it sounds like something is triggering a redirect at login, and the browser is receiving multiple session cookies (state, nonce, etc.) that are overwriting each other. This is not something that the plugin itself would cause, and is most likely the result of some sort of cookie shaping or proxy redirect handling. 9/10 times this kind of thing is due to a third-party WordPress plugin causing a conflict of some kind, but considering your environment change, it certainly sounds like there is some sort of traffic shaping happening that is causing an issue.
